export const technologyOptions = [
  "Oxford Nanopore",
  "Illumina",
  "Ion Torrent",
  "Capillary",
  "PacBio SMRT",
  "ABI SOLiD",
  "BGISEQ",
  "LS454",
  "Complete Genomics",
  "Helicos",
];

export const strategyOptions = [
  "AMPLICON",
  "ATAC-seq",
  "Bisulfite-Seq",
  "CLONE",
  "CLONEEND",
  "CTS",
  "ChIA-PET",
  "ChIP-Seq",
  "DNase-Hypersensitivity",
  "EST",
  "FAIRE-seq",
  "FINISHING",
  "FL-cDNA",
  "Hi-C",
  "MBD-Seq",
  "MNase-Seq",
  "MRE-Seq",
  "MeDIP-Seq",
  "OTHER",
  "POOLCLONE",
  "RAD-Seq",
  "RIP-Seq",
  "RNA-Seq",
  "SELEX",
  "Synthetic-Long-Read",
  "Targeted-Capture",
  "Tethered Chromatin Conformation Capture",
  "Tn-Seq",
  "VALIDATION",
  "WCS",
  "WGA",
  "WGS",
  "WXS",
  "miRNA-Seq",
  "ncRNA-Seq",
  "ssRNA-seq",
  "GBS",
];
